name: yoga_two
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter_native_splash: ^2.4.3
  animated_splash_screen: ^1.3.0
  camera: ^0.11.0+2
  audioplayers: ^6.1.0
  permission_handler: ^11.1.0
  camera_windows: ^0.2.6+1
  




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    #carousel images
    - assets/logowithimage.png
    - assets/finalicon.png
    - assets/yoga_pose1.jpeg
    - assets/yoga_pose2.jpeg
    - assets/yoga_pose3.jpeg
    - assets/yoga_pose4.jpeg
    - assets/yoga_pose5.jpeg
    - assets/yoga_pose6.jpeg
    - assets/yoga_pose7.jpeg
    - assets/yoga_pose8.jpeg
    - assets/yoga_pose9.jpeg
    - assets/yoga_pose10.jpeg
    - assets/yoga_pose11.jpeg
    - assets/yoga_pose12.jpeg
    - assets/yoga_pose13.jpeg
    - assets/yoga_pose14.jpeg
    - assets/yoga_pose15.jpeg

    #profile and logo
    - assets/profile_placeholder.png
    - assets/profile_pic.png
    - assets/poseperfect.png
    - assets/funky_icon.png
    - assets/app_logo.png
    - assets/login_logo.png

    #splash screen
    - assets/splash_bg.jpg
    - assets/splash_branding.png

    #soundscape background
    - assets/sound_forest.jpg
    - assets/sound_ocean.jpg
    - assets/sound_campfire.jpg

    #soundscape audio
    - assets/soundscape/campfire.mp3
    - assets/soundscape/ocean.mp3
    - assets/soundscape/rainforest.mp3

    #recipe background
    - assets/smoothie.jpg
    - assets/energybites.jpg
    - assets/avocadotoast.jpg

    #exercise card background
    - assets/meditation.jpg
    - assets/diet.jpg
    - assets/yoga.jpg
    - assets/tips.jpg

    #beginner yoga pose images
    - assets/beginner/beg_dog.jpg
    - assets/beginner/beg_mountain.jpg
    - assets/beginner/beg_tree.jpg
    - assets/beginner/beg_cobra.jpg
    - assets/beginner/beg_warrior1.jpg
    - assets/beginner/beg_child.jpg

    #beginner pose gifs
    - assets/beginner/gifs/child_pose.gif
    - assets/beginner/gifs/cobra_pose.gif
    - assets/beginner/gifs/mountain_pose.gif
    - assets/beginner/gifs/downward_dog.gif
    - assets/beginner/gifs/tree_pose.gif
    - assets/beginner/gifs/warrior1_pose.gif

    #advanced yoga pose images
    - assets/advanced/forearm_stand.png
    - assets/advanced/full_wheel_pose.png
    - assets/advanced/head_stand.png
    - assets/advanced/peacock_pose.png
    - assets/advanced/scorpion_pose.png
    - assets/advanced/side_crow.png

    #advanced pose gifs
    

    #intermediate yoga pose images
    - assets/intermediate/camel_pose.png
    - assets/intermediate/crow_pose.png
    - assets/intermediate/eagle_pose.png
    - assets/intermediate/king_dancer_pose.png
    - assets/intermediate/revolved_triangle_pose.png
    - assets/intermediate/warrior3_pose.png

    #intermediate yoga pose gifs




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
          weight: 700
        - asset: fonts/Poppins-Bold.ttf
          weight: 700         
        - asset: fonts/Poppins-Light.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 700
    - family: Monsterrat
      fonts:
        - asset: fonts/Montserrat.ttf
          weight: 700
    - family: League
      fonts:
        - asset: fonts/LeagueSpartan-Black.ttf
          weight: 700
        - asset: fonts/LeagueSpartan-Bold.ttf
          weight: 700         
        - asset: fonts/LeagueSpartan-ExtraBold.ttf
          weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  #flutter_native_splash
flutter_native_splash:
  color: "#ffffff" # Background color of the splash screen
  image: assets/splash_branding.png # Path to your splash screen image
  android: true
  ios: true
  web: false



