// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAclAXPt14HPKoYE9aPFmMPxVXhLuuw1eo',
    appId: '1:1075930700335:web:76b7eaa86db9d76db944da',
    messagingSenderId: '1075930700335',
    projectId: 'poseperfect-c3be7',
    authDomain: 'poseperfect-c3be7.firebaseapp.com',
    storageBucket: 'poseperfect-c3be7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3p-rEB7r2Ir1ByEM6-mh1DgHYsiu-Wuc',
    appId: '1:1075930700335:android:e55537c7c2486afdb944da',
    messagingSenderId: '1075930700335',
    projectId: 'poseperfect-c3be7',
    storageBucket: 'poseperfect-c3be7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDosn5FnBuQ91PZ0d9C0qNk6d1uSVL4Q_Q',
    appId: '1:1075930700335:ios:c5a262caa9e0f617b944da',
    messagingSenderId: '1075930700335',
    projectId: 'poseperfect-c3be7',
    storageBucket: 'poseperfect-c3be7.firebasestorage.app',
    iosBundleId: 'com.example.yogaTwo',
  );

}